/* SPDX-License-Identifier: MPL-2.0 */

#include "legacy_values.h"

#include <string.h>
#include <greek.h>
#include <dialect.h>
#include <morphflags.h>

static int legacy_flag_is_set(const unsigned char *flags, int number)
{
  const size_t index=(size_t)(number-1)/8u;
  const unsigned int bit=(unsigned int)(number-1)%8u;
  return(index < MORPHFLAG_STORAGE_BYTES &&
         (flags[index] & (unsigned char)(UINT8_C(1)<<bit)) != 0);
}

#define MAP_BIT(legacy_bit,public_bit) \
  if((legacy & (uint32_t)(legacy_bit)) != 0) result|=(public_bit)

uint32_t morpheus_public_dialect(uint32_t legacy)
{
  uint32_t result=0;
  MAP_BIT(AEOLIC,MORPHEUS_DIALECT_AEOLIC);
  MAP_BIT(ATTIC,MORPHEUS_DIALECT_ATTIC);
  MAP_BIT(DORIC,MORPHEUS_DIALECT_DORIC);
  MAP_BIT(HOMERIC,MORPHEUS_DIALECT_HOMERIC);
  MAP_BIT(IONIC,MORPHEUS_DIALECT_IONIC);
  MAP_BIT(LESBIAN,MORPHEUS_DIALECT_LESBIAN);
  MAP_BIT(NON_HOMERIC_EPIC,MORPHEUS_DIALECT_NON_HOMERIC_EPIC);
  MAP_BIT(PARADIGM,MORPHEUS_DIALECT_PARADIGM);
  MAP_BIT(PROSE,MORPHEUS_DIALECT_PROSE);
  return(result);
}

uint32_t morpheus_legacy_dialect(uint32_t public_value)
{
  uint32_t legacy=public_value;
  uint32_t result=0;
  MAP_BIT(MORPHEUS_DIALECT_AEOLIC,AEOLIC);
  MAP_BIT(MORPHEUS_DIALECT_ATTIC,ATTIC);
  MAP_BIT(MORPHEUS_DIALECT_DORIC,DORIC);
  MAP_BIT(MORPHEUS_DIALECT_HOMERIC,HOMERIC);
  MAP_BIT(MORPHEUS_DIALECT_IONIC,IONIC);
  MAP_BIT(MORPHEUS_DIALECT_LESBIAN,LESBIAN);
  MAP_BIT(MORPHEUS_DIALECT_NON_HOMERIC_EPIC,NON_HOMERIC_EPIC);
  MAP_BIT(MORPHEUS_DIALECT_PARADIGM,PARADIGM);
  MAP_BIT(MORPHEUS_DIALECT_PROSE,PROSE);
  return(result);
}

uint32_t morpheus_public_region(uint32_t legacy)
{
  uint32_t result=0;
  MAP_BIT(ARCADIA,MORPHEUS_REGION_ARCADIA);
  MAP_BIT(ARGOLID,MORPHEUS_REGION_ARGOLID);
  MAP_BIT(BOEOTIA,MORPHEUS_REGION_BOEOTIA);
  MAP_BIT(COS,MORPHEUS_REGION_COS);
  MAP_BIT(CRETE,MORPHEUS_REGION_CRETE);
  MAP_BIT(CYPRUS,MORPHEUS_REGION_CYPRUS);
  MAP_BIT(CYRENE,MORPHEUS_REGION_CYRENE);
  MAP_BIT(ELIS,MORPHEUS_REGION_ELIS);
  MAP_BIT(HERACLEA,MORPHEUS_REGION_HERACLEA);
  MAP_BIT(LACONIA,MORPHEUS_REGION_LACONIA);
  MAP_BIT(LOCRIS,MORPHEUS_REGION_LOCRIS);
  MAP_BIT(MEGARID,MORPHEUS_REGION_MEGARID);
  MAP_BIT(PHOCIS,MORPHEUS_REGION_PHOCIS);
  MAP_BIT(RHODES,MORPHEUS_REGION_RHODES);
  MAP_BIT(THERA,MORPHEUS_REGION_THERA);
  return(result);
}

uint32_t morpheus_public_person(uint32_t legacy)
{
  switch(legacy) {
  case PERS1: return(MORPHEUS_PERSON_FIRST);
  case PERS2: return(MORPHEUS_PERSON_SECOND);
  case PERS3: return(MORPHEUS_PERSON_THIRD);
  default: return(MORPHEUS_PERSON_NONE);
  }
}

uint32_t morpheus_public_number(uint32_t legacy)
{
  switch(legacy) {
  case SINGULAR: return(MORPHEUS_NUMBER_SINGULAR);
  case DUAL: return(MORPHEUS_NUMBER_DUAL);
  case PLURAL: return(MORPHEUS_NUMBER_PLURAL);
  default: return(MORPHEUS_NUMBER_NONE);
  }
}

uint32_t morpheus_public_gender(uint32_t legacy)
{
  uint32_t result=0;
  MAP_BIT(ADVERBIAL,MORPHEUS_GENDER_ADVERBIAL);
  MAP_BIT(FEMININE,MORPHEUS_GENDER_FEMININE);
  MAP_BIT(MASCULINE,MORPHEUS_GENDER_MASCULINE);
  MAP_BIT(NEUTER,MORPHEUS_GENDER_NEUTER);
  return(result);
}

uint32_t morpheus_public_case(uint32_t legacy)
{
  uint32_t result=0;
  MAP_BIT(ABLATIVE,MORPHEUS_CASE_ABLATIVE);
  MAP_BIT(ACCUSATIVE,MORPHEUS_CASE_ACCUSATIVE);
  MAP_BIT(DATIVE,MORPHEUS_CASE_DATIVE);
  MAP_BIT(GENITIVE,MORPHEUS_CASE_GENITIVE);
  MAP_BIT(NOMINATIVE,MORPHEUS_CASE_NOMINATIVE);
  MAP_BIT(VOCATIVE,MORPHEUS_CASE_VOCATIVE);
  return(result);
}

uint32_t morpheus_public_tense(uint32_t legacy)
{
  switch(legacy) {
  case PRESENT: return(MORPHEUS_TENSE_PRESENT);
  case IMPERF: return(MORPHEUS_TENSE_IMPERFECT);
  case FUTURE: return(MORPHEUS_TENSE_FUTURE);
  case AORIST: return(MORPHEUS_TENSE_AORIST);
  case PERFECT: return(MORPHEUS_TENSE_PERFECT);
  case PLUPERF: return(MORPHEUS_TENSE_PLUPERFECT);
  case FUTPERF: return(MORPHEUS_TENSE_FUTURE_PERFECT);
  case PASTABSOLUTE: return(MORPHEUS_TENSE_PAST_ABSOLUTE);
  default: return(MORPHEUS_TENSE_NONE);
  }
}

uint32_t morpheus_public_mood(uint32_t legacy)
{
  switch(legacy) {
  case CONDITIONAL: return(MORPHEUS_MOOD_CONDITIONAL);
  case GERUNDIVE: return(MORPHEUS_MOOD_GERUNDIVE);
  case IMPERATIVE: return(MORPHEUS_MOOD_IMPERATIVE);
  case INDICATIVE: return(MORPHEUS_MOOD_INDICATIVE);
  case INFINITIVE: return(MORPHEUS_MOOD_INFINITIVE);
  case OPTATIVE: return(MORPHEUS_MOOD_OPTATIVE);
  case PARTICIPLE: return(MORPHEUS_MOOD_PARTICIPLE);
  case SUBJUNCTIVE: return(MORPHEUS_MOOD_SUBJUNCTIVE);
  case SUPINE: return(MORPHEUS_MOOD_SUPINE);
  default: return(MORPHEUS_MOOD_NONE);
  }
}

uint32_t morpheus_public_voice(uint32_t legacy)
{
  uint32_t result=0;
  MAP_BIT(ACTIVE,MORPHEUS_VOICE_ACTIVE);
  MAP_BIT(PASSIVE,MORPHEUS_VOICE_PASSIVE);
  MAP_BIT(MIDDLE,MORPHEUS_VOICE_MIDDLE);
  return(result);
}

uint32_t morpheus_public_degree(
    uint32_t legacy, morpheus_part_of_speech part_of_speech,
    const unsigned char *legacy_flags)
{
  if(legacy == COMPARATIVE || legacy_flag_is_set(legacy_flags,IRREG_COMP))
    return(MORPHEUS_DEGREE_COMPARATIVE);
  if(legacy == SUPERLATIVE || legacy_flag_is_set(legacy_flags,IRREG_SUPERL))
    return(MORPHEUS_DEGREE_SUPERLATIVE);
  if(part_of_speech == MORPHEUS_PART_OF_SPEECH_ADJECTIVE)
    return(MORPHEUS_DEGREE_POSITIVE);
  return(MORPHEUS_DEGREE_NONE);
}

typedef struct {
  int legacy;
  morpheus_morph_flag public_index;
} morph_flag_mapping;

#define MORPH_FLAG(legacy_name,public_name) \
  {legacy_name,MORPHEUS_MORPH_FLAG_##public_name}

static const morph_flag_mapping morph_flag_mappings[]={
  MORPH_FLAG(ACCENT_OPTIONAL,ACCENT_OPTIONAL),
  MORPH_FLAG(A_COPUL,ALPHA_COPULATIVE),
  MORPH_FLAG(A_PRIV,ALPHA_PRIVATIVE),
  MORPH_FLAG(ANT_ACC,ANTEPENULT_ACCENT),
  MORPH_FLAG(APOCOPE,APOCOPE),
  MORPH_FLAG(ATTIC_REDUPL,ATTIC_REDUPLICATION),
  MORPH_FLAG(CAUSAL,CAUSAL),
  MORPH_FLAG(COMP_ONLY,COMP_ONLY),
  MORPH_FLAG(CONTRACTED,CONTRACTED),
  MORPH_FLAG(D_PREVB,DELTA_PREVERB),
  MORPH_FLAG(IS_DERIV,DERIVATIVE),
  MORPH_FLAG(DESIDERATIVE,DESIDERATIVE),
  MORPH_FLAG(DIMINUTIVE,DIMINUTIVE),
  MORPH_FLAG(DISSIMILATION,DISSIMILATION),
  MORPH_FLAG(DOUBLED_CONS,DOUBLED_CONSONANT),
  MORPH_FLAG(DOUBLE_AUGMENT,DOUBLE_AUGMENT),
  MORPH_FLAG(DOUBLE_REDUPL,DOUBLE_REDUPLICATION),
  MORPH_FLAG(EARLY,EARLY),
  MORPH_FLAG(ELIDE_PREVERB,ELIDED_PREVERB),
  MORPH_FLAG(ENCLITIC,ENCLITIC),
  MORPH_FLAG(ENDS_IN_DIGAMMA,ENDS_IN_DIGAMMA),
  MORPH_FLAG(EN_TO_ENI,EN_TO_ENI),
  MORPH_FLAG(FREQUENTAT,FREQUENTATIVE),
  MORPH_FLAG(GEOG_NAME,GEOGRAPHIC_NAME),
  MORPH_FLAG(GROUP_NAME,GROUP_NAME),
  MORPH_FLAG(HAS_AUGMENT,HAS_AUGMENT),
  MORPH_FLAG(HAS_PREVERB,HAS_PREVERB),
  MORPH_FLAG(IMPERSONAL,IMPERSONAL),
  MORPH_FLAG(INDECLFORM,INDECLINABLE_FORM),
  MORPH_FLAG(INTERV_S_TO_H,INTERVOCALIC_S_TO_H),
  MORPH_FLAG(INTRANS,INTRANSITIVE),
  MORPH_FLAG(IOTA_INTENS,IOTA_INTENSIVE),
  MORPH_FLAG(IRREG_COMP,IRREGULAR_COMPARATIVE),
  MORPH_FLAG(IRREGFORM,IRREGULAR_FORM),
  MORPH_FLAG(IRREG_SUPERL,IRREGULAR_SUPERLATIVE),
  MORPH_FLAG(ITERATIVE,ITERATIVE),
  MORPH_FLAG(LATE,LATE),
  MORPH_FLAG(LATER,LATER),
  MORPH_FLAG(LONG_PEN,LONG_PENULT),
  MORPH_FLAG(LOST_ACC,LOST_ACCENT),
  MORPH_FLAG(METATHESIS,METATHESIS),
  MORPH_FLAG(META_TO_PEDA,META_TO_PEDA),
  MORPH_FLAG(METRICAL_LONG,METRICALLY_LONG),
  MORPH_FLAG(NEEDS_ACCENT,NEEDS_ACCENT),
  MORPH_FLAG(NEEDS_RBREATH,NEEDS_ROUGH_BREATHING),
  MORPH_FLAG(NOT_IN_COMPOSITION,NOT_IN_COMPOSITION),
  MORPH_FLAG(NO_CIRCUMFLEX,NO_CIRCUMFLEX),
  MORPH_FLAG(NO_COMP,NO_COMPARISON),
  MORPH_FLAG(NO_REDUPL,NO_REDUPLICATION),
  MORPH_FLAG(NU_MOVABLE,NU_MOVABLE),
  MORPH_FLAG(N_INFIX,N_INFIX),
  MORPH_FLAG(PARA_TO_PARAI,PARA_TO_PARAI),
  MORPH_FLAG(PERS_NAME,PERSON_NAME),
  MORPH_FLAG(POETIC,POETIC),
  MORPH_FLAG(PRES_REDUPL,PRESENT_REDUPLICATION),
  MORPH_FLAG(PREVB_AUGMENT,PREVERB_AUGMENT),
  MORPH_FLAG(PROCLITIC,PROCLITIC),
  MORPH_FLAG(PRODELISION,PRODELISION),
  MORPH_FLAG(PROS_TO_POTI,PROS_TO_POTI),
  MORPH_FLAG(PROS_TO_PROTI,PROS_TO_PROTI),
  MORPH_FLAG(QUANT_METATHESIS,QUANTITY_METATHESIS),
  MORPH_FLAG(RARE,RARE),
  MORPH_FLAG(RAW_PREVERB,RAW_PREVERB),
  MORPH_FLAG(RAW_SONANT,RAW_SONANT),
  MORPH_FLAG(REC_ACC,RECESSIVE_ACCENT),
  MORPH_FLAG(REDUPL,REDUPLICATION),
  MORPH_FLAG(R_E_I_ALPHA,RHO_ETA_IOTA_ALPHA),
  MORPH_FLAG(ROOT_PREVERB,ROOT_PREVERB),
  MORPH_FLAG(SHORT_EIS,SHORT_EIS),
  MORPH_FLAG(SHORT_PEN,SHORT_PENULT),
  MORPH_FLAG(SHORT_SUBJ,SHORT_SUBJUNCTIVE),
  MORPH_FLAG(SIG_TO_CI,SIGMA_TO_CI),
  MORPH_FLAG(STEM_ACC,STEM_ACCENT),
  MORPH_FLAG(SUFF_ACC,SUFFIX_ACCENT),
  MORPH_FLAG(SYLL_AUGMENT,SYLL_AUGMENT),
  MORPH_FLAG(SYNCOPE,SYNCOPE),
  MORPH_FLAG(T_PREVB,TAU_PREVERB),
  MORPH_FLAG(TMESIS,TMESIS),
  MORPH_FLAG(UNASP_PREVERB,UNASPIRATED_PREVERB),
  MORPH_FLAG(UNAUGMENTED,UNAUGMENTED),
  MORPH_FLAG(UNCONTR_END,UNCONTRACTED_ENDING),
  MORPH_FLAG(UNCONTR_STEM,UNCONTRACTED_STEM),
  MORPH_FLAG(UPER_TO_UPEIR,UPER_TO_UPEIR),
  MORPH_FLAG(UPO_TO_UPAI,UPO_TO_UPAI)
};

void morpheus_public_morph_flags(
    uint8_t destination[MORPHEUS_MORPH_FLAG_CAPACITY],
    const unsigned char *legacy_flags)
{
  size_t i;
  memset(destination,0,MORPHEUS_MORPH_FLAG_CAPACITY);
  for(i=0;i<sizeof morph_flag_mappings/sizeof morph_flag_mappings[0];i++) {
    const morpheus_morph_flag index=morph_flag_mappings[i].public_index;
    if(legacy_flag_is_set(legacy_flags,morph_flag_mappings[i].legacy))
      destination[index/8u]|=(uint8_t)(UINT8_C(1)<<(index%8u));
  }
}

#undef MORPH_FLAG
#undef MAP_BIT
